// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/yang/2/vial-qmk/keyboards/qp_display_only/gfx/gif128x128_girl1.gif --output /home/yang/2/vial-qmk/keyboards/qp_display_only/gfx --format rgb565 --no-rle False --no-deltas True`

#pragma once

#include <qp.h>

extern const uint32_t gfx_gif128x128_girl1_length;
extern const uint8_t  gfx_gif128x128_girl1[497550];
