#define VIAL_KEYBOARD_UID {0x2E, 0xE6, 0x0E, 0x23, 0x34, 0xEF, 0x99, 0x37}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define RGBLED_NUM    3
#define PHY_INDICATOR_NUM    2
#define INDICATOR_FUNCT    {(1<<USB_LED_CAPS_LOCK), (1<<USB_LED_NUM_LOCK)}
#define INDICATOR_VAL    96

#undef  LCD_ROTATION
#define LCD_ROTATION QP_ROTATION_180

#define WEAR_LEVELING_BACKING_SIZE 65536 //MAX Value