#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_ESCAPE, KC_GRAVE, KC_1, KC_NO, KC_2, KC_F1, KC_F2, KC_3},
    {KC_LGUI, KC_A, KC_Q, KC_NONUS_BSLASH, KC_LCTRL, KC_LSHIFT, KC_CAPSLOCK, KC_TAB},
    {KC_F3, KC_4, KC_F4, KC_5, KC_F5, KC_F6, KC_6, KC_7},
    {KC_X, KC_R, KC_D, KC_E, KC_LALT, KC_Z, KC_S, KC_W},
    {KC_T, KC_Y, KC_F7, KC_8, KC_U, KC_F8, KC_9, KC_I},
    {KC_N, KC_SPACE, KC_H, KC_B, KC_V, KC_G, KC_C, KC_F},
    {KC_F9, KC_0, KC_O, KC_F10, KC_MINUS, KC_P, KC_EQUAL, KC_LBRACKET},
    {KC_SCOLON, KC_L, KC_DOT, KC_RALT, KC_COMMA, KC_M, KC_K, KC_J},
    {KC_F11, KC_F12, KC_BSPACE, KC_RBRACKET, KC_BSPACE, KC_BSLASH, KC_NO, KC_NO},
    {KC_ENTER, KC_UP, KC_RSHIFT, KC_DOWN, KC_LEFT, LT(1, KC_APPLICATION), KC_SLASH, KC_QUOTE},
    {KC_PGUP, KC_DELETE, KC_NO, KC_HOME, KC_NUMLOCK, KC_KP_7, KC_PSCREEN, KC_KP_SLASH},
    {KC_KP_5, KC_KP_2, KC_NO, KC_KP_4, KC_KP_1, KC_KP_0, KC_RIGHT, KC_PGDOWN},
    {KC_KP_8, KC_SCROLLLOCK, KC_PAUSE, KC_KP_ASTERISK, KC_KP_MINUS, KC_KP_9, KC_KP_PLUS, KC_NO},
    {KC_KP_6, KC_KP_3, KC_KP_ENTER, KC_KP_DOT, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, RGB_TOG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {RGB_VAD, KC_TRNS, RGB_VAI, RGB_SAD, RGB_HUD, RGB_SAI, KC_CALC, RGB_HUI},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_TRNS, KC_MPRV},
    {KC_TRNS, KC_TRNS, KC_VOLU, KC_TRNS, KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_TRNS, KC_TRNS, KC_NO, KC_NO},
    {KC_TRNS, KC_PGUP, KC_TRNS, KC_PGDOWN, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_INSERT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_END, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};
