#include QMK_KEYBOARD_H

#define USER04 0x7E04
#define USER05 0x7E05
#define MAGIC_TOGGLE_NKRO 0x7013

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_GRAVE, KC_1, KC_2, KC_F1, KC_F2, KC_F3, KC_F4, KC_3},
    {KC_LGUI, KC_A, KC_Q, KC_NONUS_BSLASH, KC_LCTRL, KC_LSHIFT, KC_CAPSLOCK, KC_TAB},
    {KC_4, KC_F5, KC_F6, KC_F7, KC_F8, KC_5, KC_6, KC_7},
    {KC_X, KC_R, KC_D, KC_E, KC_LALT, KC_Z, KC_S, KC_W},
    {KC_T, KC_Y, KC_8, KC_F9, KC_9, KC_0, KC_U, KC_I},
    {KC_N, KC_SPACE, KC_H, KC_B, KC_V, KC_G, KC_C, KC_F},
    {KC_MINUS, KC_O, KC_F12, KC_DELETE, KC_HOME, KC_PGUP, KC_EQUAL, KC_P},
    {KC_SCOLON, KC_L, KC_DOT, KC_RALT, KC_COMMA, KC_M, KC_K, KC_J},
    {KC_LBRACKET, KC_PGDOWN, USER04, KC_RIGHT, KC_BSPACE, KC_BSLASH, KC_RBRACKET, KC_BSLASH},
    {KC_ENTER, KC_UP, KC_RSHIFT, KC_DOWN, KC_LEFT, MO(1), KC_SLASH, KC_QUOTE},
    {KC_ESCAPE, KC_F10, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_MS_L, KC_BTN1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, RGB_TOG, KC_MS_R, KC_BTN2, KC_TRNS, KC_TRNS, KC_MS_D, KC_MS_U},
    {RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {RGB_VAD, KC_TRNS, RGB_VAI, RGB_SAD, RGB_HUD, RGB_SAI, KC_CALC, RGB_HUI},
    {KC_TRNS, USER05,  KC_TRNS, KC_INSERT, KC_PSCREEN, KC_SCROLLLOCK, USER04, KC_MPLY},
    {KC_TRNS, KC_TRNS, KC_VOLU, KC_TRNS, KC_VOLD, KC_MUTE, MAGIC_TOGGLE_NKRO, KC_TRNS},
    {KC_MPRV, KC_PAUSE, KC_TRNS, KC_END, KC_TRNS, KC_TRNS, KC_MNXT, KC_TRNS},
    {KC_TRNS, KC_PGUP, KC_TRNS, KC_PGDOWN, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};
